
POST  {{baseUrl}}/question/create HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
  "answer": 2,
  "examId":"659c4a3923ba2e9c1d3cbf0e",
  "options":["bad","good", "best"],
  "question": "how is javascrpt"
}
