
name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your main branch or the branch you want to trigger the action

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build the Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/my-image:latest .
        working-directory: ./

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ github.repository }}/my-image:latest
